"""Single transport boundary shared by audio and gimbal control."""

from typing import Protocol

from ..domain.audio import AudioPacket, AudioStreamTelemetry
from ..domain.control import GimbalSetpoint, SerialLinkStatus
from ..protocol.messages import StreamStart


class DeviceLink(Protocol):
    def start(self) -> None: ...

    def close(self) -> None: ...

    def publish_gimbal(self, setpoint: GimbalSetpoint) -> None: ...

    def start_audio_stream(self, parameters: StreamStart) -> None: ...

    def send_audio(self, packet: AudioPacket) -> None: ...

    def stop_audio_stream(self) -> None: ...

    def set_mute(self, enabled: bool) -> None: ...

    def set_volume(self, permille: int) -> None: ...

    def serial_status(self) -> SerialLinkStatus: ...

    def audio_status(self) -> AudioStreamTelemetry: ...
